import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import servicesRouter from "./services";
import locationsRouter from "./locations";
import requestsRouter from "./requests";
import offersRouter from "./offers";
import messagesRouter from "./messages";
import ratingsRouter from "./ratings";
import pointsRouter from "./points";
import commissionRangesRouter from "./commission-ranges";
import supportRouter from "./support";
import notificationsRouter from "./notifications";
import cmsRouter from "./cms";
import analyticsRouter from "./analytics";
import bannersRouter from "./banners";
import adminDatabaseRouter from "./admin-database";
import uploadRouter from "./upload";
import pushTokensRouter from "./push-tokens";
import pageBackgroundsRouter from "./page-backgrounds";
import eventsRouter from "./events";
import firebaseConfigRouter from "./firebase-config";
import swDiagRouter from "./sw-diag";
import maintenanceRouter from "./maintenance";
import loyaltyRouter from "./loyalty";
import founderRouter from "./founder";
import introScreensRouter from "./intro-screens";
import invoicesRouter from "./invoices";
import techModificationsRouter from "./tech-modifications";
import seoRouter from "./seo";

const router: IRouter = Router();

router.use(uploadRouter);
router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(servicesRouter);
router.use(locationsRouter);
router.use(requestsRouter);
router.use(offersRouter);
router.use(messagesRouter);
router.use(ratingsRouter);
router.use(pointsRouter);
router.use(commissionRangesRouter);
router.use(supportRouter);
router.use(notificationsRouter);
router.use(cmsRouter);
router.use(analyticsRouter);
router.use(bannersRouter);
router.use(adminDatabaseRouter);
router.use(pushTokensRouter);
router.use(pageBackgroundsRouter);
router.use(eventsRouter);
router.use(firebaseConfigRouter);
router.use(swDiagRouter);
router.use(maintenanceRouter);
router.use(loyaltyRouter);
router.use(founderRouter);
router.use(introScreensRouter);
router.use(invoicesRouter);
router.use(techModificationsRouter);
router.use(seoRouter);

export default router;
