// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bottom-nav/CustomerBottomNav.tsx": () => import("../components/mockups/bottom-nav/CustomerBottomNav.tsx"),
  "./components/mockups/bottom-nav/TechnicianBottomNav.tsx": () => import("../components/mockups/bottom-nav/TechnicianBottomNav.tsx"),
  "./components/mockups/notification-icons/YouWereSelectedPreview.tsx": () => import("../components/mockups/notification-icons/YouWereSelectedPreview.tsx")
};
